### ISSUE TITLE
License Please

### ISSUE THREAD

**Issue by fragmuffin** [MaJerle/c-code-style#14]
# Problem Description
This project has no `LICENSE` file at its root.

Technically I believe this makes it your intellectual property, and others that find it shouldn't assume you're willing to share it... I'm no lawyer, but if this were a software project, it wouldn't be OSS without a license.

## Assumption : Intended to be open (?)

I'm assuming you're happy for people to share and use this for their own projects openly... either way, if your intent for this standard is:

- `open`: an open license is necessary for people to use it legally
- `closed`: a license stating that you'd like to be contacted before it's copied would also be helpful to those that find it.

**Comment by EmbeddedLife615** [comment]
邮件已收到，我会尽快回复的！
